### ISSUE TITLE
How much speed up should be expected after weight pruning?

### ISSUE THREAD

**Issue by cyu0913** [fatchord/WaveRNN#104]
Does weight pruning result in significant speed up during inference?

**Comment by fatchord** [comment]
@cyu0913 At the minute I'm concentrating on the gpu side of things for wavernn - where pruning has questionable advantages given the time investment (it's a pretty light model to begin with). If you're interested in the cpu side of things please check out LPCnet: https://github.com/mozilla/LPCNet or gening's https://github.com/geneing/WaveRNN-Pytorch
