### ISSUE TITLE
For real time generation 

### ISSUE THREAD

**Issue by rishikksh20** [fatchord/WaveRNN#11]
Hi, thanks for such a good implementation of WaveRNN. Actually, I am working to integrate this WaveRNN implementation with Tacotron for TTS task and I got good results way faster then Wavenet but way slower than real-time (10 sec audio in nearly 3 mins or so).
Currently what I see that this model gives around 1500 samples/sec with my GTX 1080 ti. But in WaveRNN paper they claim to get 96,000 samples/sec by optimising WaveRNN-896 to P100 GPU even they show subscale to mobile CPU. Is it possible to optimize this WaveRNN at that level, so that we get real-time sampling at least from GPU.

**Comment by geneing** [comment]
Checkout batch generation discussion in the "new model paper/details" issue.

**Comment by rishikksh20** [comment]
@fatchord Is it possible to train this model with keithito's tacotron for TTS without any major changes ?

**Comment by fatchord** [comment]
@rishikksh20 I haven't used that repo but as long as it has the option to generate ground truth aligned features then you should be able to use it. It only takes a couple of hours to finetune the model in this repo to work with 'blurry' TTS outputs.

**Comment by rishikksh20** [comment]
@fatchord sounds good, the problem with Tacotron 1 is that it generate complete duration mels even though silence exits it won't trim/stop at the end of the speech. If my speech is 5 sec long it generate mels of complete 20 sec(if my default generation of mels is 20 sec) in which only 5 sec contain exists and rest is silence. So we can trim manually by conversion mels to audio and detect silence that what every Tacotron 1 implementation do now but how we can trim mels itself do you know any technique ?

**Comment by fatchord** [comment]
@rishikksh20 You can use a simple threshold to stop generating silence at the end of utterance in tacotron. It works just as well as predicting a stop token in my experience.
