### ISSUE TITLE
xfade_and_unfold input parameter error

### ISSUE THREAD

**Issue by candlewill** [fatchord/WaveRNN#110]
As the output of WaveRNN is wave samples, I think this line should be modified as the following code:

```python
output = self.xfade_and_unfold(output, target * self.hop_length, overlap * self.hop_length)
```

https://github.com/fatchord/WaveRNN/blob/b178948a031fa9f19e428956c71b3ce3ec5d2a3e/models/fatchord_version.py#L230

@fatchord Is this right?

**Comment by fatchord** [comment]
@candlewill The way I have it is right - I want target and overlap to be configurable from the hparms and argparse.
