### ISSUE TITLE
error when running preprocess.py

### ISSUE THREAD

**Issue by 12ben** [fatchord/WaveRNN#113]
10 wav files found in ".\wavefiles"

+-------------+-----------+--------+------------+-----------+
| Sample Rate | Bit Depth | Mu Law | Hop Length | CPU Count |
+-------------+-----------+--------+------------+-----------+
|    22050    |     9     |  True  |    275     |     6     |
+-------------+-----------+--------+------------+-----------+

10 wav files found in ".\wavefiles"

10 wav files found in ".\wavefiles"

10 wav files found in ".\wavefiles"

10 wav files found in ".\wavefiles"

10 wav files found in ".\wavefiles"

10 wav files found in ".\wavefiles"

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\win\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\tools\WaveRNN-master\preprocess.py", line 39, in process_wav
    np.save(f'{paths.mel}{id}.npy', m, allow_pickle=False)
  File "C:\Users\win\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\npyio.py", line 517, in save
    fid = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'data//Wu_mol/mel/.\\wavefiles\\wavs\\A1.npy'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 74, in <module>
    for i, (id, length) in enumerate(pool.imap_unordered(process_wav, wav_files), 1):
  File "C:\Users\win\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 735, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: 'data//Wu_mol/mel/.\\wavefiles\\wavs\\A1.npy'

**Comment by MRS-OBAMA** [comment]
I had a similar error, i fixed it by having the wav_path as an absolute path such as
`C:\\Users\\User\\WaveRNN\\WavFiles\\`
 and by changing the following in preprocess.py:
```
def process_wav(path):
    id = path.split('/')[-1][:-4] # <-- changed this to split \\ instead 
    m, x = convert_file(path)
    np.save(f'{paths.mel}{id}.npy', m, allow_pickle=False)
    np.save(f'{paths.quant}{id}.npy', x, allow_pickle=False)
    return id, m.shape[-1]```
