### ISSUE TITLE
quick_start.py get_r not defined and generated speech rate is too fast

### ISSUE THREAD

**Issue by JungShinPlusPlus** [fatchord/WaveRNN#117]
Hi. 
I'm using Ubuntu 16.04 and tried this quick_start.py
Installed Pytorch 1.1
(tried 1.01 but some functions were missing: torch.nn.functional.one_hot)

It stopped running at:
r = tts_model.get_r()
Saying get_r is not defined. But I could see tts_model has a property 'r'.
so I tried:
r = tts_model.r
And it ran and produced wav files.

However the speaking rate of the wav file is really fast (wav attached). Is this expected?
[1_batchedTrue_180k.wav.zip](https://github.com/fatchord/WaveRNN/files/3430011/1_batchedTrue_180k.wav.zip)

Best Regards,

Jung

**Comment by fatchord** [comment]
Hi Jung, the last merge created a few problems. I've reverted it for the time being. Try cloning again and it should work ok.

**Comment by JungShinPlusPlus** [comment]
Thanks for the fast update! :)
I updated the code and it ran without issue and generated wav files have normal speaking rate.

Case closed!

**Comment by KonstantinosMarko** [comment]
what was the problem that was causing the fast speech rate? thank you!
