### ISSUE TITLE
What is purpose of get_gru_cell?

### ISSUE THREAD

**Issue by mrgloom** [fatchord/WaveRNN#119]
I can't get it why we need `get_gru_cell`?
https://github.com/fatchord/WaveRNN/blob/3f5a96ea61b952996ce71c012f860b72f86aee9b/models/fatchord_version.py#L160
Seems it's just transforms `nn.GRU` to `nn.GRUCell`, why it's not needed for `forward`, but needed for `generate`?

**Comment by fatchord** [comment]
In the context of generating samples one by one, the gru cell is a lot more efficient.

**Comment by mrgloom** [comment]
Is it related to `flatten_parameters`?
