### ISSUE TITLE
Noisy silence in the synthesized speech

### ISSUE THREAD

**Issue by wangfn** [fatchord/WaveRNN#134]
Hi Fatchord,

First of all, thanks a lot for sharing such a great work.

I followed your alternative version of wavernn with 10 logistic mixtures, using the same hyper parameters as listed in the hparams.py except that I did silence trimming, the synthesis works great for speech part, however I noticed noisy silence in some synthesized speech files. In one of my tests, 11 out of 200 speech files contain such a noisy silence. If I redo the synthesis with a different random seed value, the noisy silence disappear, seems that this behavior is quite random. But I never notice it in the "raw" bit wavernn model.

I did spend time to understand the reason, but no clue so far. So do you by any chance notice such noisy silences in your generated speech files? Do you have any idea what causes the issue? Thanks a lot in advance.

**Comment by wangfn** [comment]
Hi Fatchord, a sample file is attached:

![noisy_silence_from_wavernn_mol](https://user-images.githubusercontent.com/12064184/64493811-38fb7e00-d285-11e9-824a-66458b58bc6c.png)

**Comment by fatchord** [comment]
@wangfn Often times when I encounter artifacts like this, the first thing I try is to train for another epoch or so. It might just need to be popped out of bad local minima.

**Comment by fatchord** [comment]
@wangfn any luck with this? Did training it for a little bit longer help at all?

**Comment by wangfn** [comment]
@fatchord Not really. For similar glitches that are present at the speech part, training longer helps.  However the mentioned stochastic behaviour still exists at the silences, though not a lot. Seems that the trained model is not robust for low value inputs. I'll do few more experiments by manipulating the hyper parameters. In case unlucky, I'll apply post processing to remove them.

**Comment by rishikksh20** [comment]
@wangfn I also have same issue, it is very common problem. the best approach is either change Tacotron checkpoint like use different checkpoint to generate male and use same wavernn checkpoint for generating wav or vice-versa.

**Comment by wangfn** [comment]
@rishikksh20 Indeed, the issue is somehow common for MoL, more than 5% of my testing samples have this issue. The solution you mentioned is workable to remove those glitches, I did similar tricks.

**Comment by angusturner** [comment]
Bumping this issue, as I have noticed it too. Specifically, random blips in quality (like white noise), that a most common in quiet audio regions. I've had problems when using MoL on Wavenet in the past. I wonder if anyone knows how to reliably fix this, or if MoL is simply less robust?
