### ISSUE TITLE
WaveRNN training speed

### ISSUE THREAD

**Issue by thiagomcoutinho** [fatchord/WaveRNN#138]
I'm getting ~1.1step/s on an GTX1080, with python 3.6 and torch 1.0. 
My gpu usage is aprox 40%(with nvidia-smi) and the CPU threads are definitely being used.

Tacotron model trained well, using 100% of GPU.

Any thoughts on what could be wrong? In theory I should be getting 3steps/s since I'm on GTX1080.

Thanks.

**Comment by TinBarbie** [comment]
I have the same issue getting ~0.3steps/s on an RTX 2060, python 3.7 and torch 1,7.
The gpu usage is only around 45%.
Could anyone help? 
Many thanks.
