### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by loretoparisi** [fatchord/WaveRNN#15]
Thanks a lot for this implementation. It would be great to provide pre-trained models for the generated samples.

**Comment by fatchord** [comment]
@loretoparisi I haven't trained the models on any open source datasets so I'm not sure what the legal situation is with the weights I have regarding distribution. I'll err on the side of caution for now - sorry.

**Comment by loretoparisi** [comment]
@fatchord thank you, this is a good point. Having a domain transformation from the input dataset to the model, this will depend on the data usage agreement you have and any point about data transformation that could or could not be mentioned. By the way, assuming you have followed the paper, which was the dataset structure? This could help me to find open source datasets and do a training from scratch. Thank you very much.

**Comment by geneing** [comment]
I have a pretrained model using LJSpeech dataset in my fork of this repo: (https://github.com/geneing/WaveRNN).

**Comment by rishikksh20** [comment]
@fatchord how much hours of audio needed to generate good voice like your demo voice?

**Comment by fatchord** [comment]
@rishikksh20 I used around 20 hours of data. One thing to note is that I used Tacotron 1 for those samples in my demo voice.

**Comment by fatchord** [comment]
I'll be uploading a pretrained model today or tomorrow.
