### ISSUE TITLE
Unaligned fades in batched generation

### ISSUE THREAD

**Issue by 742617000027** [fatchord/WaveRNN#150]
During investigating possible causes for #149, we came across a potential bug in the way batched audio is concatenated in `fatchord_version.py`'s `xfade_and_unfold()` function. The following figures show the shape of the fades that are applied to each batch entry before concatenation:

**Fade-In**
![image](https://user-images.githubusercontent.com/15521878/67719286-d6e00f00-f9d1-11e9-8324-12859f386d65.png)

**Fade-Out**
![image](https://user-images.githubusercontent.com/15521878/67719348-f4ad7400-f9d1-11e9-8ef9-e0a90c4ea962.png)

**Squared fades applied to impulse train**
![image](https://user-images.githubusercontent.com/15521878/67720731-09d7d200-f9d5-11e9-9b4c-888b82539a06.png)

Due to the way the fades are constructed, the ramps are not aligned and the signals are not mixed with equal power. Instead, two successive zero values are introduced in the output signal within the overlap region between batch entries. In the following figures, vertical red lines mark zero values (i.e. _exactly_ 0) in the signal:

**Zeros on borders between batch entries**
![0_Samples_Full](https://user-images.githubusercontent.com/15521878/67719976-2a069180-f9d3-11e9-8fef-b6ddcc6f1f77.png)

**Close up**
![0_Samples_Close](https://user-images.githubusercontent.com/15521878/67720056-56baa900-f9d3-11e9-9f7f-3ddaf440a838.png)

To fix the issue, we changed the way `fade_out` is constructed to the following:
```
silence_len = overlap // 2
fade_len = overlap - silence_len
linear = np.ones((silence_len), dtype=np.float64)
t = np.linspace(-1, 1, fade_len, dtype=np.float64)
fade_out = np.sqrt(0.5 * (1 - t))
fade_out = np.concatenate([linear, fade_out])
```

This assumes that preceding silence is only needed for the fade-in, to account for the RNN warmup. It results in the following fade-out:

**New fade-out**
![image](https://user-images.githubusercontent.com/15521878/67720505-65559000-f9d4-11e9-9e9f-a8a2d078df80.png)

**Squared fades (old fade-in and new fade-out) applied to impulse train**
![image](https://user-images.githubusercontent.com/15521878/67720754-1fe59280-f9d5-11e9-8d52-2a370fbb8f84.png)

**Comment by fatchord** [comment]
@742617000027 I think you're right! I'll test this out. Thanks for the heads up

**Comment by fatchord** [comment]
That's fixed now in https://github.com/fatchord/WaveRNN/commit/544cd5d53156b0beefe9607e4eae9daafed8170d
