### ISSUE TITLE
WaveRNN generated blabbering speech

### ISSUE THREAD

**Issue by sih4sing5hong5** [fatchord/WaveRNN#159]
Thank you for this great work!

We plan to do open source Taioanoe TTS system with our [open dataset](https://suisiann-dataset.ithuan.tw/) and open source [scripts](https://github.com/Sui-Siann-Dataset/HunLian/tree/fSymbols/fatchord-WaveRNN) for language equality.

But our WaveRNN model generated blabbering speech when silence.

There is sample in 875k generated in training.
https://soundcloud.com/user-202918673/sets/taioanoe-blabbering-wavernn

There is our [hparams.py](https://github.com/Sui-Siann-Dataset/HunLian/blob/fSymbols/fatchord-WaveRNN/tshamsoo/hparams.py)
```
# DSP --------------------------------------------------------------------------------------------------------------#

# Settings for all models
sample_rate = 22050
n_fft = 2048
fft_bins = n_fft // 2 + 1
num_mels = 80
hop_length = 275                    # 12.5ms - in line with Tacotron 2 paper
win_length = 1100                   # 50ms - same reason as above
fmin = 40
min_level_db = -100
ref_level_db = 20
bits = 9                            # bit depth of signal
mu_law = True                       # Recommended to suppress noise if using raw bits in hp.voc_mode below
peak_norm = False                   # Normalise to the peak of each wav file


# WAVERNN / VOCODER ------------------------------------------------------------------------------------------------#


# Model Hparams
voc_mode = 'MOL'                    # either 'RAW' (softmax on raw bits) or 'MOL' (sample from mixture of logistics)
voc_upsample_factors = (5, 5, 11)   # NB - this needs to correctly factorise hop_length
voc_rnn_dims = 512
voc_fc_dims = 512
voc_compute_dims = 128
voc_res_out_dims = 128
voc_res_blocks = 10

# Training
voc_batch_size = 32
voc_lr = 1e-4
voc_checkpoint_every = 25_000
voc_gen_at_checkpoint = 5           # number of samples to generate at each checkpoint
voc_total_steps = 1_000_000         # Total number of training steps
voc_test_samples = 50               # How many unseen samples to put aside for testing
voc_pad = 2                         # this will pad the input so that the resnet can 'see' wider than input length
voc_seq_len = hop_length * 5        # must be a multiple of hop_length
voc_clip_grad_norm = 4              # set to None if no gradient clipping needed

# Generating / Synthesizing
voc_gen_batched = True              # very fast (realtime+) single utterance batched generation
voc_target = 11_000                 # target number of samples to be generated in each batch entry
voc_overlap = 550                   # number of samples for crossfading between batches
```

Because of max_length of mel, we choose around 4 hrs audio with shorter wav,

Tacotron in 193k got pretty good audio quality with some electronic noise.
There are tactron attention and mel_plot in 193k(maybe different from audio above):

![193321](https://user-images.githubusercontent.com/5996555/69832908-b2df4a00-126b-11ea-8551-11b580f2c96c.png)
![192882](https://user-images.githubusercontent.com/5996555/69832911-b7a3fe00-126b-11ea-8a20-c0639b0e7e8c.png)

How can we fix this blabbering problem? Clipping silence in dataset or tracing code?

Thank you for any suggestions!

**Comment by fatchord** [comment]
Thanks for your kind words @sih4sing5hong5 !

The only time I've heard that kind of blabbering is from unconditioned wavernn. That suggests something has gone very wrong if that's the result of tacotron+wavernn. Are the wavs and the corresponding text correct? 

Anyway, I think the first thing you could do is to crop out the silence at the start and end of your samples. I've found that this generally helps tacotron attention. 

If some of your samples have a very long silence in the middle of the sentence I would also recommend removing them, or at least the very worst ones.

**Comment by sih4sing5hong5** [comment]
Thank you for quick reply!
We will clip silence and retrain. It may consume 2~3 weeks.
We will report and release model if succeed.

**Comment by fatchord** [comment]
Oh my! 2-3 weeks -  why would it take so long? You can automate the silence removal with the librosa function or use something more sophisticated like webrtcvad.

**Comment by sih4sing5hong5** [comment]
Some audios contain multiple sentences, and there are `1~2` secs silence. We removed silence after kaldi word-alignment, and done yesterday. Thank you for your suggestion, we should use librosa early. We are interesting what is the proper length for silence. Is `0.1~0.5` secs?

At the same time, the wavernn training with old corpus have finished with `MOL` mode. The audio generated is [noisy](https://soundcloud.com/user-202918673/wavernn-diverage). We retrained wavernn with `MOL` mode, got the same noisy audio. We modified the mode to `RAW`, got [wonderful result](https://soundcloud.com/user-202918673/sets/wavernn-with-raw-mode)!. When should we choose `MOL` mode, when for `RAW`?

For these models, we noticed the tacotron cannot learn tone sandhi greatly with 4 hrs dataset. We are translating writing text to surface form before tacotron.

Thank you for this open source repos!

**Comment by fatchord** [comment]
Regarding input length, I'm thinking you would need much more than 0.5 secs. From experience I'd say 1 - 10 secs is a good range of length to shoot for. 

As for the RAW v MOL. Definitely go with RAW when you are starting out. MOL takes a very long time to train and training can sometimes go sideways.

**Comment by sih4sing5hong5** [comment]
> Regarding input length, I'm thinking you would need much more than 0.5 secs. From experience I'd say 1 - 10 secs is a good range of length to shoot for.
> 
> As for the RAW v MOL. Definitely go with RAW when you are starting out. MOL takes a very long time to train and can sometimes go sideways.

Thank you for your reply! We will adjust our corpus for better training result!
