### ISSUE TITLE
tts samples 

### ISSUE THREAD

**Issue by lfogliantis** [fatchord/WaveRNN#16]
Hi fatchord, great work - may I ask for the tts samples that you posted, did you use the vocoder trained on the ground truths or on the output of a seq2seq text to features vector model?

**Comment by ZohaibAhmed** [comment]
Same question here, @lfogliantis did you have any luck?

**Comment by G-Wang** [comment]
Given the unique sentences he generated for his example audios, I'd guess he's using a text to Mel front end, as many of those types of sentences wouldn't exist in any open source data such as audio book.

So a front end model like tacotron or deepvoice.

**Comment by fatchord** [comment]
@lfogliantis I used my own implementation of Tacotron to generate the sentences.
