### ISSUE TITLE
Some files are not being generated using "force_gta" parameter

### ISSUE THREAD

**Issue by titocaco** [fatchord/WaveRNN#200]
First, I have preprocessed my own dataset using this:

`python preprocess.py --path <path_to_my_dataset>`

Then, I have trained the Tacotron model using this:

`python train_tacotron.py`

After I have trained the Tacotron model using the default parameters for my own dataset, I have tried to train the WaveRNN using this command:

`python train_wavernn.py --gta`

but I have received a FileNotFoundError for a file in "WaveRNN/data/gta" directory. Indeed, the file was not there, and I don't know why, so, to generate the GTA files, I executed this command:

`python train_tacotron.py --force_gta`

I thought it would be solved now, so I have executed this command again:

`python train_wavernn.py --gta`

Unfortunately, it didn't generate all of them, because I have faced the same FileNotFoundError again, but for a different file at this time. It seems to generate only some GTA files and, for some reason, this seems to be preventing WaveRNN training from continuing, as it appears to depend on GTA files that have not been generated.

Please, what I am doing wrong here?

**Comment by greatforu** [comment]
Hi is it solved now?
