### ISSUE TITLE
Description of the fatchord_version wavernn

### ISSUE THREAD

**Issue by wsstriving** [fatchord/WaveRNN#212]
Hi,
      Since the fatchord_version is very different from the original paper, do you have any detailed description of the design behind this version? Thanks a lot
Sam

**Comment by fatchord** [comment]
Hi @wsstriving ,thank you for your interest -  there was a discussion a while back in the issues which should give you a little more context. I'm working a lot  at the minute so I don't have much time to spend on this project (and the issues here) unfortunately. 

https://github.com/fatchord/WaveRNN/issues/9

**Comment by wsstriving** [comment]
Thanks a lot!
