### ISSUE TITLE
 why is randint?

### ISSUE THREAD

**Issue by hdmjdp** [fatchord/WaveRNN#25]
mel_offsets = [np.random.randint(0, offset) for offset in max_offsets]

why is randint?

**Comment by fatchord** [comment]
@hdmjdp This is because the training samples are longer than the number of timesteps that are backpropagated through time. So collate function uses `randint` to get a random timestep inside whatever 'wiggle room' is available in the spectrogram.

**Comment by hdmjdp** [comment]
@fatchord thanks, but I use hop_size=120, this may cause "out of index", so if there some methods?
"
     pad = 2
    mel_win = hp.seq_len // hp.hop_size + 2 * pad

    max_offsets = [x[0].shape[-1] - (mel_win + 2 * pad) for x in batch]   
    mel_offsets = [np.random.randint(0, offset) for offset in max_offsets]
    # mel_offsets = [np.random.randint(0, int(offset * 0.8)) for offset in max_offsets]
    sig_offsets = [(offset + pad) * hp.hop_size for offset in mel_offsets]
    
    mels = [x[0][:, mel_offsets[i]:mel_offsets[i] + mel_win] \
            for i, x in enumerate(batch)]
    
    coarse = [x[1][sig_offsets[i]:sig_offsets[i] + hp.seq_len + 1] \
              for i, x in enumerate(batch)]
    
"
i just multply 0.8 to solve this problem:
    mel_offsets = [np.random.randint(0, int(offset * 0.8)) for offset in max_offsets]

**Comment by hdmjdp** [comment]
@fatchord Did you have better methods?thansks!

**Comment by geneing** [comment]
@hdmjdp did you regenerate training set after changing hop_size? When mel spectrograms are generated, hop_size is one of the parameters. If you change hop_size and don't regenerate mel spec data, it will be inconsistent and you'll get out of index problem. Also, notice that upsampling filter sizes are also tied to the  hop_size (product of upsampling filter multipliers has to match closely the hop size). If I understand this code correctly, of course....
