### ISSUE TITLE
“ a much simpler version and will upload soon.”，can  this version  run in realtime in cpu? 

### ISSUE THREAD

**Issue by hdmjdp** [fatchord/WaveRNN#28]
You remind me “ a much simpler version and will upload soon.”， can  this version  run in realtime in cpu? 
I have changed your model to smaller one(only has 0.95M parameters).

**Comment by fatchord** [comment]
@hdmjdp I'm still working on the simplified model and the results are pretty good so far (more params than your 0.95M though) ... also experimenting with batched inference on GPU.

**Comment by bliep** [comment]
@hdmjdp _"I have changed your model to smaller one(only has 0.95M parameters)."_
Would like to have a look, want to share that model?

**Comment by hdmjdp** [comment]
@fatchord in the picture, your can see a bar, how can i remove it?
![image](https://user-images.githubusercontent.com/26831425/49487643-5f1b6a00-f87e-11e8-98af-674ed70a687a.png)

[0002_wavernn.zip](https://github.com/fatchord/WaveRNN/files/2647018/0002_wavernn.zip)

**Comment by fatchord** [comment]
@hdmjdp I updated the current model in the repo to generate realtime on gpu. Check out notebook 4b.
