### ISSUE TITLE
Subscaling WaveRNN

### ISSUE THREAD

**Issue by G-Wang** [fatchord/WaveRNN#3]
Hello,

Thanks for the great work!

Any plans for subscaling WaveRNN implementation? Or is the current WaveRNN implementation already fast enough (compared to say WaveNet generation)?

**Comment by fatchord** [comment]
Thanks for your kind words. Right now I'm still working on conditioning - and after that I'll be looking at pruning the model. Considering how long it takes to train this model and the fact that I have only one 8gb gpu it will most likely be a while before I get to look at subscaling. 

As far as generation speed goes - in its current unoptimised form, it's generating at around 1100 samples/second. Much faster than non-parallel wavenet but still a way to go for real-time generation.
