### ISSUE TITLE
about "Pruning - Scratchpad.ipynb"

### ISSUE THREAD

**Issue by hdmjdp** [fatchord/WaveRNN#30]
have you try train your model with sparse method? how about the result?

**Comment by fatchord** [comment]
@hdmjdp I haven't trained with pruning yet. I'm still writing the code/reading papers.

**Comment by fatchord** [comment]
I reckon just keep applying the mask calculated at 200k steps for the rest of training - at least that's what I'm getting from the paper.

**Comment by hdmjdp** [comment]
@fatchord thanks, I think as same as you. I think in the "model" class of  Pruning - Scratchpad.ipynb: you do not need to add self.prune in "forward " function.

**Comment by bjtommychen** [comment]
@fatchord @hdmjdp FYI. I did pruning on well-trained original model weeks ago.  with loss increased 1% from the smallest value, the prune ratio stop at 93% for the top5 matrix, ~ 92% of total parameters.

**Comment by bjtommychen** [comment]
@hdmjdp I only pruned the original model.  the original model's output wave is not good quality one, but almost same as the pruned one. I think the Alternative model's output is better. 
                ('R.weight', 0.93),
                ('O1.weight', 0.93),
                ('O3.weight', 0.93),
                ('I_coarse.weight', 0.93),
                ('I_fine.weight', 0.93),

**Comment by CorentinJ** [comment]
Does the pruning help the inference speed at all? I'm not noticing any difference on my end.
