### ISSUE TITLE
About input to gru

### ISSUE THREAD

**Issue by azraelkuan** [fatchord/WaveRNN#31]
hi, i have a question about the input in this picture:
![image](https://user-images.githubusercontent.com/23380152/50068711-dc8d9580-0201-11e9-8fd1-e3d03a177dd8.png)
the `x` is a float number, if we concat `x` and `mel`, the weight of x will be very small, why not use the `ulaw` input and `one_hot` it

**Comment by fatchord** [comment]
@azraelkuan I'm not sure I understand you 100%. Why is the weight of x small in this case? 

As for one-hot - that works fine with the model. The only thing is that it creates a bigger input matmul.

**Comment by azraelkuan** [comment]
@fatchord my misunderstanding! the input of one hot only have one value the same as yours
