### ISSUE TITLE
have you try subscale generate?

### ISSUE THREAD

**Issue by hdmjdp** [fatchord/WaveRNN#35]
have you try subscale generate?

**Comment by fatchord** [comment]
@hdmjdp I haven't mainly because simple batched inference works quite well even without subscaling.

**Comment by bjtommychen** [comment]
@fatchord If I generate many wave files, it would be batched. but for one wave file, how to batch to speed up. Thanks.

**Comment by fatchord** [comment]
@bjtommychen I've updated notebook 4b - have a look at that and you'll see I added a couple of methods to the model class to enable simple batched inference on a single wav file.

**Comment by hdmjdp** [comment]
@fatchord I think there will be some loss in overlap part wav.

**Comment by fatchord** [comment]
@hdmjdp There's some small degradation of sound quality - however that order of magnitude speed up is a kinda hard to ignore!
