### ISSUE TITLE
Faster implementation of WaveRNN and licensing

### ISSUE THREAD

**Issue by mkotha** [fatchord/WaveRNN#38]
Hi, I managed to make the implementation of WaveRNN much faster by allowing it to use cuDNN's implementation of GRU:

https://github.com/mkotha/WaveRNN

The code is based on yours, although I have heavily modified it.

I'd like to make the above code publicly available, either dedicated to the public domain or released under an open source license. However, I realize that you didn't release your code under an open source license. Would it be possible for me to get a permission to release the code?

**Comment by fatchord** [comment]
@mkotha Yeah there's no problem - I'll update this repo with a generic open source license now. 

Can I open an issue on your repo? I just have a couple of questions about condition in your version.

**Comment by mkotha** [comment]
Thank you very much!

> Can I open an issue on your repo? I just have a couple of questions about conditioning in your version.

Of course. Please go ahead.
