### ISSUE TITLE
mu-law during generation

### ISSUE THREAD

**Issue by CorentinJ** [fatchord/WaveRNN#39]
I am companding my target waveform with a mu-law before quantization. However I am not sure if I should expand the signal during the autoregressive generation or leave it as such, and expand it once the entire signal is generated.

I see that the restoration of the quantized signal happens here:
https://github.com/fatchord/WaveRNN/blob/16aa2edd25313d4c6828f8bb9342225eee322bf3/NB4b%20-%20Alternative%20Model%20(Training).ipynb#L502
My question is whether I should expand signal from the mu-law right after this line, e.g.:
`sample = torch.sign(sample) * (1 / (2 ** bits - 1)) * ((1 + (2 ** bits - 1)) ** torch.abs(sample) - 1)`

**Comment by CorentinJ** [comment]
After a bit of thinking, I figured out that I probably want to compand the signal at preprocessing time, use the companded signal during training and generation and only expand the generated signal after it is entirely generated. Is this correct?

**Comment by fatchord** [comment]
@CorentinJ Yeag your intuition is correct - you want to invert mu-law once the entire signal is generated.

**Comment by CorentinJ** [comment]
Great, thank you.
