### ISSUE TITLE
conditioning on Mel Spectrogram

### ISSUE THREAD

**Issue by G-Wang** [fatchord/WaveRNN#4]
Hello,

I was wondering if there is any implementation for conditioning on mel spectrogram (from say Tacatron 2)?

**Comment by fatchord** [comment]
Hi there, I'm working on it. The model is slow to train on my 8gb gpu but I'm hoping I'll get there eventually.

**Comment by rishikksh20** [comment]
@fatchord is it possible now to integrate WaveRNN with Tacotron or Deep Voice.

**Comment by HyperGD1994** [comment]
hi, i m confused about how to add mel spectrogram condition to WaveRNN, the paper seems not mention it. do you have some idea to solve it? thanks

**Comment by jjj8080** [comment]
Hey do you have any updates on this?

**Comment by fatchord** [comment]
@G-Wang @rishikksh20 @HyperGD1994 @jjj8080 Conditioned network is uploaded - Check it out :)
