### ISSUE TITLE
What model take as input?

### ISSUE THREAD

**Issue by mrgloom** [fatchord/WaveRNN#42]
Here is some samples https://fatchord.github.io/model_outputs/ but I wonder what model takes as input? Is it ground truth Mel Spectrogram or it's predicted Mel Spectrogram by something like Tacotron2?

**Comment by fatchord** [comment]
@mrgloom The samples under the heading 'Neural TTS output' are predicted mels from my own offline implementation of Tacotron 1 paper. The samples further down the page under heading 'Vocoder output' are from ground truth mels (test set).
