### ISSUE TITLE
Effect of Resnet CNN (aux) features.

### ISSUE THREAD

**Issue by erogol** [fatchord/WaveRNN#43]
I plotted CNN output of my trained model. It does not seem to be useful to me. Do you see something maybe I am missing? Or have you tried without Resnet features?
![image](https://user-images.githubusercontent.com/1402048/55170895-abfdb600-5177-11e9-8821-a44c646c6443.png)

**Comment by fatchord** [comment]
@erogol Well there's only one way to know for sure - have you tried training without it?

**Comment by erogol** [comment]
@fatchord no, i was asking the same though. Then, i should try.

**Comment by fatchord** [comment]
@ misread your question - apologies. Haven't trained it without resnet.
