### ISSUE TITLE
Finetuning with gta helpful?

### ISSUE THREAD

**Issue by cyu0913** [fatchord/WaveRNN#52]
Have you got observable improvements after fine-tuning with gta features? In my experiments, the quality of generated speech doesn't improve compared to the ones using the model just trained with ground truth mel-spectrogram.

**Comment by fatchord** [comment]
@cyu0913 Yes, I noticed the noise level decreases and there are less artifacts when training on gta features.

**Comment by cyu0913** [comment]
I see. Thanks a lot!
