### ISSUE TITLE
python3 quick_start.py: "ModuleNotFoundError: No module named 'models.fatchord_wavernn'"

### ISSUE THREAD

**Issue by vitaly-zdanevich** [fatchord/WaveRNN#54]
Full stack trace:
```
Traceback (most recent call last):
  File "quick_start.py", line 2, in <module>
    from models.fatchord_wavernn import Model
ModuleNotFoundError: No module named 'models.fatchord_wavernn'
```

Current `master` branch.

**Comment by fatchord** [comment]
@vitaly-zdanevich I can't reproduce that error on my machine. I cloned it just now and ran quick_start.py without any problems. Not sure what I can do here.

**Comment by vitaly-zdanevich** [comment]
Created empty file `__init__.py` in `models` and this error has gone. Please check on Python 3.6.7, if you want to support this version, looks like on another machine with Python 3.7.3 I do not have this problem.

But now I see another error, I do not know if this is related somehow with the previous one:
```
$ python3 quick_start.py 
/home/vitaly_zdanevich/.local/lib/python3.6/site-packages/numba/errors.py:105: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)

Initialising WaveRNN Model...

Trainable Parameters: 4.481M
Traceback (most recent call last):
  File "quick_start.py", line 60, in <module>
    sample_rate=hp.sample_rate)()
  File "/home/vitaly_zdanevich/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 2 required positional arguments: 'x' and 'mels'
```

**Comment by vitaly-zdanevich** [comment]
No, I checked on another fresh machine - this is not a problem with Python 3.6, I do not know where.

**Comment by fatchord** [comment]
@vitaly-zdanevich Yeah I just created an environment for python 3.6.7 and it all works fine. The only problem is that matplotlib is missing from requirements.txt so I'll push that fix soon. 

Anyway, I'll leave this issue open - maybe someone else will get the same problem.
