### ISSUE TITLE
Multi GPU support 

### ISSUE THREAD

**Issue by saibharani** [fatchord/WaveRNN#61]
I tried to wrap model in nn.DataParallel() in train_tacotron.py file but it gives me error can you tell how to implement multi gpu

**Comment by fatchord** [comment]
@saibharani I only have the one gpu so I can't help out on this.

**Comment by TheButlah** [comment]
@saibharani This will be fixed as soon as #109 is free of bugs and merged, but if you need to you can try that PR out now.
