### ISSUE TITLE
error  when run "train_wavernn.py" with bits=16

### ISSUE THREAD

**Issue by peter05010402** [fatchord/WaveRNN#62]
@fatchord  I  run "train_wavernn.py"  with bits=16 on P100 GPU, then got "CUDA out of memory"
Then,  when I set voc_batch_size = 8, got error as follow:
Initialising Model...

Trainable Parameters: 37.838M

Loading Weights: "checkpoints/ljspeech_9bit_mulaw.wavernn/latest_weights.pyt"

+------------+------------+--------+--------------+-----------+
| Remaining  | Batch Size |   LR   | Sequence Len | GTA Train |
+------------+------------+--------+--------------+-----------+
| 500k Steps |     8      | 0.0001 |     1375     |   True    |
+------------+------------+--------+--------------+-----------+
 
Traceback (most recent call last):
  File "train_wavernn.py", line 109, in <module>
    voc_train_loop(voc_model, optimiser, train_set, test_set, lr, total_steps)
  File "train_wavernn.py", line 35, in voc_train_loop
    loss.backward()
  File "tensorflow-GPU/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "tensorflow-GPU/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

**Comment by fatchord** [comment]
@peter05010402 I just updated the WaveRNN model to train with mixture of logistics - try that instead.

**Comment by peter05010402** [comment]
@fatchord Thank you!!!
