### ISSUE TITLE
The gta finetune doesn't improve speech quality

### ISSUE THREAD

**Issue by candlewill** [fatchord/WaveRNN#63]
I compared the wavernn model with and without finetune training, found there's no significant improvement in speech quality. @fatchord Did you compared these two, and have the same result?

**Comment by fatchord** [comment]
@candlewill When using raw bits as wavernn output I found that gta did improve audio quality on a dataset of male voice with low pitch. The improvement wasn't as noticeable with LJSpeech. 

However when using the mixture of logistics I can't see much if any improvement with gta irrespective of dataset. So perhaps it isn't necessary with MOL.

**Comment by candlewill** [comment]
Thanks for your reply.

**Comment by MorganCZY** [comment]
May I ask what the GTA means？

**Comment by gyanr0425** [comment]
@MorganCZY It means Ground Truth Alignment.
