### ISSUE TITLE
Mixture of Logistics Model

### ISSUE THREAD

**Issue by TomGledhill** [fatchord/WaveRNN#66]
Hello @fatchord ! Thank you a lot for hosting this great project!
Seems like pretrained model in pretrained directory is trained in RAW mode.
Could you please also share pretrained weights of Mixture of Logistics Model?
Thanks!

**Comment by fatchord** [comment]
@TomGledhill Sure, I'll be uploading MOL wavernn weights tomorrow.

**Comment by fatchord** [comment]
@TomGledhill I just uploaded pretrained MOL model.

**Comment by oytunturk** [comment]
In my opinion, the new models (ljspeech.tacotron.r2.180k.zip, ljspeech.wavernn.mol.800k.zip) are not working as good as the old ones (ljspeech.tacotron.r1.196k.zip, ljspeech.wavernn.gta.800k.zip) in terms of prosody. If you inspect the pitch contours and compare with previously released pre-trained model outputs, you will see that the new version results in more flat f0 contours (significantly lower standard deviation) as well as lower mean f0 which makes the voice sound less lively. This applies to both batched and unbatched inference results.
