### ISSUE TITLE
Quickstart results differ from those in model_outputs

### ISSUE THREAD

**Issue by acrosson** [fatchord/WaveRNN#69]
Hi @fatchord thanks for putting this together.

I just ran the `quickstart.py` script and I'm noticing the results differ from those found [https://fatchord.github.io/model_outputs/](https://fatchord.github.io/model_outputs/)

I ran the following:
```
python quick_start.py -u --input_text "The position of the page on the paper should be considered if the book is to have a satisfactory look."
```

Do I need to change the parameters to get a similar result?

**Comment by fatchord** [comment]
@acrosson That's a different model to the one currently in the pretrained folder. 

Also since there's noise generated inside the model at inference you'll always get different outputs even on the same model.

**Comment by acrosson** [comment]
How was the model in your samples trained for “WavRNN Vocoder Only”? It says it was trained for 800k, as does the one in the pretrained folder. I get there will be noise which causes slight variations. But the one in your sample folder has better pronunciation and emphasis than what is being generated from QuickStart. What changed need to be made during training?

**Comment by fatchord** [comment]
@acrosson the samples labeled "WaveRNN Vocoder Only" are from ground truth mels, there is no TTS/tacotorn model involved. That's probably why they sound better.

**Comment by acrosson** [comment]
Got it. And is it possible to sample from ground truth mels for certain words, and use generated mels for the others, and piece them all together before sending to WaveRNN?
