### ISSUE TITLE
How was the model in samples "TTS+wavernn" 

### ISSUE THREAD

**Issue by guojm14** [fatchord/WaveRNN#75]
I ran the quick_start script but the results sound noisy. How many steps should I train to reproduce your results in your samples?  Thank you!

**Comment by fatchord** [comment]
@guojm14 They should sound pretty similar. Can you attach a zip file with the samples generated?

**Comment by guojm14** [comment]
Sorry, I mistakely used my manually modified pytorch. The voice sounds great when using official pytorch. Thank you very much and I will close this issue.
