### ISSUE TITLE
Introducing speaker embeddings

### ISSUE THREAD

**Issue by oytunturk** [fatchord/WaveRNN#76]
Does anyone have insights on how to introduce speaker information into Tacotron and WaveRNN training to learn multi-speaker and/or speaker-independent models? I have started experimenting with introducing one-hot encoded speaker identities as input to Tacotron. Other ideas might include:
1) Passing speaker identity information as input to hidden encoder layers and/or into attention mechanism instead of input layer
2) Extracting soft speaker embedding vectors using the output of final layers of a speaker recognition network (such as DeepSpeaker) and using them to provide speaker identity information instead of one-hot encoding
I think databases such as VCTK or LibriSpeech/LibriTTS could be appropriate for this purpose. Do we know if the training time is roughly linear with training corpus size assuming model architecture and hyperparameters stay the same?

**Comment by fatchord** [comment]
@oytunturk in one of the prosody tacotron papers they concatenated speaker embeddings to the encoder output. I'm actually working on this by the way :)

**Comment by oytunturk** [comment]
Nice! I'll share any insights I have as well then @fatchord. Introducing prosody embeddings may also be a good idea to explore to improve expressiveness.

**Comment by arijitx** [comment]
@fatchord great work. Is there any progress on having the current codebase in a multi speaker setup ? Thanks :)
