### ISSUE TITLE
Loss decreases but cannot learn attention

### ISSUE THREAD

**Issue by gmltmd789** [fatchord/WaveRNN#77]
Hi, thank you for providing Tacotron, modified WaveRNN code.
When I cloned your code and trained your Tacotron code with LJSpeech, I found that output attention was abnormal.
![110289](https://user-images.githubusercontent.com/49265950/57818562-621c6e00-77bf-11e9-9d41-8bc63b1cf4f6.png)
There is any diagonal line in here, for 110k steps. 
I don't know why this happened.  I didn't change your code.

Thank for the repo.

**Comment by fatchord** [comment]
@gmltmd789 The current version of the repo uses location-based attention and I've found that it sometimes doesn't learn attention - I'm still trying to figure out why. For now, a rule of thumb - if the model doesn't learn in under 10k steps, you need to start training a new model.
