### ISSUE TITLE
Sequence length for train

### ISSUE THREAD

**Issue by begeekmyfriend** [fatchord/WaveRNN#78]
I notice that the sequence length of each mel clip is about 9 times of hop size and the location selected is random. The evaluation is OK basically but the problem is that there seems discontinuity in the waveform. I think it is the sequence length and selection lead to such issue. Should I expand the sequence length or even feed the whole length of mel clip for training? Meanwhile the batch size shall be reduced to 4.
![image](https://user-images.githubusercontent.com/6031938/57906018-134c0280-78ab-11e9-8222-3630c9267ddf.png)

**Comment by fatchord** [comment]
@begeekmyfriend 

> The evaluation is OK basically but the problem is that there seems discontinuity in the waveform. I think it is the sequence length and selection lead to such issue.

What's your thinking behind this reasoning? 

> Should I expand the sequence length or even feed the whole length of mel clip for training? Meanwhile the batch size shall be reduced to 4.

I guess you could - but it would take a long time to train. Also, off the top of my head, I think that in the WaveRNN paper they trained on a sequence of around 960. That's even less than what I am using (1375).

**Comment by begeekmyfriend** [comment]
Solved by https://github.com/begeekmyfriend/WaveRNN/commit/05f01820a1900b433dc11d4eb79818849f2859f6
It does nothing with the sequence length. Closing it.
