### ISSUE TITLE
current_step update bug?

### ISSUE THREAD

**Issue by bayesrule** [fatchord/WaveRNN#79]
Hi, I have to say a big thank you first for sharing such a great repo!

In file train_tacotron.py,
I think line 133 
```Python
current_step = model.get_step()
```
should be moved to somewhere within the loop of line 137

```Python
for session in hp.tts_schedule :
```
Otherwise, the current_step variable wouldn't be updated. I think train_wavernn.py does it correctly.

Cheers,

**Comment by fatchord** [comment]
@bayesrule Well spotted and thanks! I've fix it locally and will be pushing (a ton of commits) hopefully inside a week.
