### ISSUE TITLE
predicted speed is 1075 samples/sec, sr =  16000, upsample_factors=(5,5,8) , is slow than you demo!

### ISSUE THREAD

**Issue by maozhiqiang** [fatchord/WaveRNN#8]
hi @fatchord , I training with you implement , but slow than your demo! where is wrong! thanks!
Generating: 1/3
43101/43200 -- Speed: 638 samples/sec
Generating: 2/3
56901/57000 -- Speed: 1075 samples/sec
Generating: 3/3
110501/110600 -- Speed: 1067 samples/sec

**Comment by fatchord** [comment]
@maozhiqiang What gpu are you using? I'm using a 1080gtx for reference.

**Comment by maozhiqiang** [comment]
@fatchord I'm using 1060gtx
