### ISSUE TITLE
A bit confusion on the features that are used for training WaveRNN..

### ISSUE THREAD

**Issue by dipjyoti92** [fatchord/WaveRNN#83]
@fatchord  First of all, thank you so much for your implementation. It would a great help if you could kindly clarify two things:

1/
In the samples page (https://fatchord.github.io/model_outputs/), for the samples under the title "WaveRNN + TTS Outputs", was it trained only with the mel spectrograms output of the tacotron or was it first trained with ground truth mel spectrograms and then train again with output of the tacotron?

I understand that for the samples under the title "WavRNN Vocoder Only", it was only trained with ground truth mel spectrograms.

2/ when we train using the command "python train_wavernn.py --gta", does the gta features (location: data/ljspeech_9bit_mulaw/gta/ )corresponds to the only mel spectrograms output of the tacotron ? or Does this training also considers the ground truth mel spectrograms (location: data/ljspeech_9bit_mulaw/mel/).

I would be highly grateful if you could kindly clarify these questions. Thanks in advance.

**Comment by fatchord** [comment]
@dipjyoti92 I'll try my best to answer your questions:

1 - I'm pretty sure that those samples (they're a bit old now) were generated with a WaveRNN that was trained on ground truth mels first and then later with a GTA dataset generated by tacotron. I haven't purged the binaries from this repo (yet!) so the pre-trained weights are in there if you want to dig through the commits - I think that it was trained 400k on ground truth and then 400k on tacotron gta if my memory serves me correctly. 

2 - The tacotron gta output is still teacher forced by ground truth mels. So yes, they are still involved in the process but ultimately the features in that /gta/ folder are tacotron's output.

If you need further clarification let me know.
