### ISSUE TITLE
Run train_tacotron.py got Error when fft_bins=1025

### ISSUE THREAD

**Issue by peter05010402** [fatchord/WaveRNN#95]
Run train_tacotron.py got Error when fft_bins=1025

<img width="573" alt="未命名" src="https://user-images.githubusercontent.com/42974031/59088376-e040e000-8939-11e9-98c9-9b3c208ead81.png">

**Comment by fatchord** [comment]
@peter05010402 I've modified tacotron so that the postnet outputs mels, not stft spectrograms.

**Comment by peter05010402** [comment]
@fatchord Thank you for quick reply!
 which committs is your modified tacotron?

_, m, attention = tts_model.generate(x)
m is mel spectrograms?
