### ISSUE TITLE
gen_tacotron got noise voice

### ISSUE THREAD

**Issue by jinfagang** [fatchord/WaveRNN#96]
this is pretrained model tacotron voice result

[2_batchedTrue_180k.zip](https://github.com/fatchord/WaveRNN/files/3293222/2_batchedTrue_180k.zip)

it's seems all noise data but not voice

**Comment by fatchord** [comment]
@jinfagang Is that sample produced by the quick_start.py script?

**Comment by jinfagang** [comment]
@fatchord  No, simply generated by tacotron model.

**Comment by fatchord** [comment]
@jinfagang The pretrained models are automatically loaded in only for the quick_start.py script. The gen_tacotron.py file is for your own models (although you can overwrite the weights in the checkpoints folder with the pretrained weights if you wish).

**Comment by 18harsh** [comment]
I am also getting the same issue
